// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControl.proto

package com.bdfint.rpc.fgsb;

/**
 * Protobuf enum {@code fgsb.CodeState}
 */
public enum CodeState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SUCCESS = 0;</code>
   */
  SUCCESS(0),
  /**
   * <code>TOKEN_INVALID = 1;</code>
   */
  TOKEN_INVALID(1),
  /**
   * <code>ACCOUNT_PWD_ERROR = 2;</code>
   */
  ACCOUNT_PWD_ERROR(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SUCCESS = 0;</code>
   */
  public static final int SUCCESS_VALUE = 0;
  /**
   * <code>TOKEN_INVALID = 1;</code>
   */
  public static final int TOKEN_INVALID_VALUE = 1;
  /**
   * <code>ACCOUNT_PWD_ERROR = 2;</code>
   */
  public static final int ACCOUNT_PWD_ERROR_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CodeState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CodeState forNumber(int value) {
    switch (value) {
      case 0: return SUCCESS;
      case 1: return TOKEN_INVALID;
      case 2: return ACCOUNT_PWD_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CodeState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CodeState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CodeState>() {
          public CodeState findValueByNumber(int number) {
            return CodeState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.bdfint.rpc.fgsb.CameraControlProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final CodeState[] VALUES = values();

  public static CodeState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CodeState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fgsb.CodeState)
}

