// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControl.proto

package com.bdfint.rpc.fgsb;

public interface SimpleReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fgsb.SimpleReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  int getType();
}
