// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControl.proto

package com.bdfint.base.sys.util.asuync;

public interface SimpleReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fgsb.SimpleReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>int32 type = 2;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   *卸料点id
   * </pre>
   *
   * <code>string unloadingPointId = 3;</code>
   * @return The unloadingPointId.
   */
  String getUnloadingPointId();
  /**
   * <pre>
   *卸料点id
   * </pre>
   *
   * <code>string unloadingPointId = 3;</code>
   * @return The bytes for unloadingPointId.
   */
  com.google.protobuf.ByteString
      getUnloadingPointIdBytes();

  /**
   * <pre>
   *识别单id
   * </pre>
   *
   * <code>string recognizeSheetId = 4;</code>
   * @return The recognizeSheetId.
   */
  String getRecognizeSheetId();
  /**
   * <pre>
   *识别单id
   * </pre>
   *
   * <code>string recognizeSheetId = 4;</code>
   * @return The bytes for recognizeSheetId.
   */
  com.google.protobuf.ByteString
      getRecognizeSheetIdBytes();

  /**
   * <pre>
   *摄像头地址
   * </pre>
   *
   * <code>string cameraAddr = 5;</code>
   * @return The cameraAddr.
   */
  String getCameraAddr();
  /**
   * <pre>
   *摄像头地址
   * </pre>
   *
   * <code>string cameraAddr = 5;</code>
   * @return The bytes for cameraAddr.
   */
  com.google.protobuf.ByteString
      getCameraAddrBytes();

  /**
   * <pre>
   *预制点是否从最初开始	
   * </pre>
   *
   * <code>bool resetPreset = 6;</code>
   * @return The resetPreset.
   */
  boolean getResetPreset();
}
