// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraControl.proto

package com.bdfint.base.sys.util.asuync;

/**
 * Protobuf enum {@code fgsb.SimpleReqType}
 */
public enum SimpleReqType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *proto3. first must be 0, and other should not be same
   * </pre>
   *
   * <code>Start_PTZ = 0;</code>
   */
  Start_PTZ(0),
  /**
   * <pre>
   *吸盘检测
   * </pre>
   *
   * <code>Start_Sucker_Detection = 1;</code>
   */
  Start_Sucker_Detection(1),
  /**
   * <pre>
   *警示灯服务	
   * </pre>
   *
   * <code>WARNING_LIGHT_SERVICE = 2;</code>
   */
  WARNING_LIGHT_SERVICE(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *proto3. first must be 0, and other should not be same
   * </pre>
   *
   * <code>Start_PTZ = 0;</code>
   */
  public static final int Start_PTZ_VALUE = 0;
  /**
   * <pre>
   *吸盘检测
   * </pre>
   *
   * <code>Start_Sucker_Detection = 1;</code>
   */
  public static final int Start_Sucker_Detection_VALUE = 1;
  /**
   * <pre>
   *警示灯服务	
   * </pre>
   *
   * <code>WARNING_LIGHT_SERVICE = 2;</code>
   */
  public static final int WARNING_LIGHT_SERVICE_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static SimpleReqType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SimpleReqType forNumber(int value) {
    switch (value) {
      case 0: return Start_PTZ;
      case 1: return Start_Sucker_Detection;
      case 2: return WARNING_LIGHT_SERVICE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SimpleReqType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SimpleReqType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SimpleReqType>() {
          public SimpleReqType findValueByNumber(int number) {
            return SimpleReqType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return CameraControlProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final SimpleReqType[] VALUES = values();

  public static SimpleReqType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SimpleReqType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:fgsb.SimpleReqType)
}

