# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CameraAI.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CameraAI.proto',
  package='fgsb',
  syntax='proto3',
  serialized_options=b'\n\026com.bdfint.rpc.fgsb.aiB\rCameraAIProtoP\001\242\002\004FGAI',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x43\x61meraAI.proto\x12\x04\x66gsb\"{\n\tAIKeyInfo\x12\x18\n\x10unloadingPointId\x18\x01 \x01(\t\x12\x18\n\x10recognizeSheetId\x18\x02 \x01(\t\x12\x10\n\x08presetId\x18\x03 \x01(\x05\x12\x14\n\x0cisLastPreset\x18\x04 \x01(\x08\x12\x12\n\ncameraAddr\x18\x05 \x01(\t\"P\n\x05\x41IReq\x12 \n\x07keyInfo\x18\x01 \x01(\x0b\x32\x0f.fgsb.AIKeyInfo\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x17\n\x0fimageObjectName\x18\x03 \x01(\t\"R\n\x05\x41IRes\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12 \n\x07keyInfo\x18\x03 \x01(\x0b\x32\x0f.fgsb.AIKeyInfo\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t*=\n\x06\x41IType\x12\x0e\n\nHEART_BEAT\x10\x00\x12\r\n\tRECOGNIZE\x10\x01\x12\x14\n\x10SUCKER_DETECTION\x10\x02\x32\x33\n\x08\x43\x61meraAI\x12\'\n\tGetResult\x12\x0b.fgsb.AIReq\x1a\x0b.fgsb.AIRes\"\x00\x42\x30\n\x16\x63om.bdfint.rpc.fgsb.aiB\rCameraAIProtoP\x01\xa2\x02\x04\x46GAIb\x06proto3'
)

_AITYPE = _descriptor.EnumDescriptor(
  name='AIType',
  full_name='fgsb.AIType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEART_BEAT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RECOGNIZE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCKER_DETECTION', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=315,
  serialized_end=376,
)
_sym_db.RegisterEnumDescriptor(_AITYPE)

AIType = enum_type_wrapper.EnumTypeWrapper(_AITYPE)
HEART_BEAT = 0
RECOGNIZE = 1
SUCKER_DETECTION = 2



_AIKEYINFO = _descriptor.Descriptor(
  name='AIKeyInfo',
  full_name='fgsb.AIKeyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unloadingPointId', full_name='fgsb.AIKeyInfo.unloadingPointId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recognizeSheetId', full_name='fgsb.AIKeyInfo.recognizeSheetId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='presetId', full_name='fgsb.AIKeyInfo.presetId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isLastPreset', full_name='fgsb.AIKeyInfo.isLastPreset', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cameraAddr', full_name='fgsb.AIKeyInfo.cameraAddr', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=147,
)


_AIREQ = _descriptor.Descriptor(
  name='AIReq',
  full_name='fgsb.AIReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyInfo', full_name='fgsb.AIReq.keyInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='fgsb.AIReq.type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageObjectName', full_name='fgsb.AIReq.imageObjectName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=229,
)


_AIRES = _descriptor.Descriptor(
  name='AIRes',
  full_name='fgsb.AIRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='fgsb.AIRes.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='fgsb.AIRes.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keyInfo', full_name='fgsb.AIRes.keyInfo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='fgsb.AIRes.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=313,
)

_AIREQ.fields_by_name['keyInfo'].message_type = _AIKEYINFO
_AIRES.fields_by_name['keyInfo'].message_type = _AIKEYINFO
DESCRIPTOR.message_types_by_name['AIKeyInfo'] = _AIKEYINFO
DESCRIPTOR.message_types_by_name['AIReq'] = _AIREQ
DESCRIPTOR.message_types_by_name['AIRes'] = _AIRES
DESCRIPTOR.enum_types_by_name['AIType'] = _AITYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AIKeyInfo = _reflection.GeneratedProtocolMessageType('AIKeyInfo', (_message.Message,), {
  'DESCRIPTOR' : _AIKEYINFO,
  '__module__' : 'CameraAI_pb2'
  # @@protoc_insertion_point(class_scope:fgsb.AIKeyInfo)
  })
_sym_db.RegisterMessage(AIKeyInfo)

AIReq = _reflection.GeneratedProtocolMessageType('AIReq', (_message.Message,), {
  'DESCRIPTOR' : _AIREQ,
  '__module__' : 'CameraAI_pb2'
  # @@protoc_insertion_point(class_scope:fgsb.AIReq)
  })
_sym_db.RegisterMessage(AIReq)

AIRes = _reflection.GeneratedProtocolMessageType('AIRes', (_message.Message,), {
  'DESCRIPTOR' : _AIRES,
  '__module__' : 'CameraAI_pb2'
  # @@protoc_insertion_point(class_scope:fgsb.AIRes)
  })
_sym_db.RegisterMessage(AIRes)


DESCRIPTOR._options = None

_CAMERAAI = _descriptor.ServiceDescriptor(
  name='CameraAI',
  full_name='fgsb.CameraAI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=378,
  serialized_end=429,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetResult',
    full_name='fgsb.CameraAI.GetResult',
    index=0,
    containing_service=None,
    input_type=_AIREQ,
    output_type=_AIRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERAAI)

DESCRIPTOR.services_by_name['CameraAI'] = _CAMERAAI

# @@protoc_insertion_point(module_scope)
